title: Falcode docuentation
description: Falcode documentation page for organization information and standards.
theme: just-the-docs

url: https://just-the-docs.github.io

logo: "/assets/Logo-Full.png"
favicon_ico: "/assets/Iso-Full.png"

search_enabled: true
